//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_03_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.Timers = new HashSet<Timer>();
        }
    
        public int AreaId { get; set; }
        public Nullable<int> TypeArea { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> NoSplit { get; set; }
        public Nullable<bool> AssemblyArea { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> MultipleOrders { get; set; }
        public Nullable<bool> HiddenArea { get; set; }
        public string IP { get; set; }
        public int PavilionId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> OrderExecution { get; set; }
        public Nullable<int> Dependence { get; set; }
        public Nullable<int> WorkingPeople { get; set; }
        public Nullable<int> ComponentTypeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> Segment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timer> Timers { get; set; }
    }
}
