//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_03_WPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRCMS_newEntities1 : DbContext
    {
        public CRCMS_newEntities1()
            : base("name=CRCMS_newEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Timer> Timers { get; set; }
        public virtual DbSet<TimerArchive> TimerArchives { get; set; }
        public virtual DbSet<TimerInactivity> TimerInactivities { get; set; }
        public virtual DbSet<TimerInactivityArchive> TimerInactivityArchives { get; set; }
    }
}
