//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_03_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Timers = new HashSet<Timer>();
            this.TimerArchives = new HashSet<TimerArchive>();
            this.TimerInactivities = new HashSet<TimerInactivity>();
            this.TimerInactivityArchives = new HashSet<TimerInactivityArchive>();
        }
    
        public int DocumentId { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> DocumentCreateDate { get; set; }
        public Nullable<System.DateTime> DocumentCloseDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public Nullable<int> StockId { get; set; }
        public string MachinesSN { get; set; }
        public Nullable<decimal> HoursMachines { get; set; }
        public string Description { get; set; }
        public string SmcsCode { get; set; }
        public string ComponentSN { get; set; }
        public Nullable<System.DateTime> ComponentDismantlingDate { get; set; }
        public Nullable<decimal> PartsCost { get; set; }
        public Nullable<decimal> WorkCost { get; set; }
        public Nullable<decimal> ConsumablesCost { get; set; }
        public Nullable<bool> ApprovedServiceEngineer { get; set; }
        public Nullable<int> EngineModelId { get; set; }
        public Nullable<decimal> ComponentHours { get; set; }
        public Nullable<int> RepairTypeId { get; set; }
        public Nullable<System.DateTime> ArrivalMonth { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> DeliveryMethodId { get; set; }
        public Nullable<bool> ToPlan { get; set; }
        public Nullable<int> CabinetSE { get; set; }
        public Nullable<bool> IsArrived { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timer> Timers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimerArchive> TimerArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimerInactivity> TimerInactivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimerInactivityArchive> TimerInactivityArchives { get; set; }
    }
}
