//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_03_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerInactivity
    {
        public int TimerInactivityId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<int> DurationInSeconds { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Comment { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
